# Generated by Django 5.0.6 on 2024-07-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_data_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='plugin',
            field=models.CharField(blank=True, help_text='Plugin to use for this network', max_length=255, null=True, unique=True, verbose_name='Plugin'),
        ),
    ]
