# Generated by Django 5.0.6 on 2024-10-09 11:34

import wis2box_adl.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_station_wmo_station_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='wmo_block_number',
            field=models.PositiveIntegerField(blank=True, help_text='WMO block number', null=True, verbose_name='WMO Block Number'),
        ),
        migrations.AlterField(
            model_name='station',
            name='wmo_station_number',
            field=models.CharField(blank=True, help_text='WMO station number', null=True, validators=[wis2box_adl.core.utils.validate_as_integer], verbose_name='WMO Station Number'),
        ),
    ]
