# Generated by Django 5.0.6 on 2024-07-18 02:38

import wis2box_adl.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_station_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataparameter',
            name='parameter',
            field=models.CharField(choices=wis2box_adl.core.utils.get_data_parameters_as_choices, max_length=255, unique=True, verbose_name='Parameter'),
        ),
    ]
