# Generated by Django 5.0.6 on 2024-10-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_station_wmo_block_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='wmo_block_number',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='WMO block number', null=True, verbose_name='WMO Block Number'),
        ),
    ]
