# Generated by Django 5.0.6 on 2024-07-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dataparameter_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataingestionrecord',
            name='uploaded_to_wis2box',
            field=models.BooleanField(default=False, verbose_name='Uploaded to WIS2BOX'),
        ),
    ]
