# Generated by Django 5.0.6 on 2024-07-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dataingestionrecord_uploaded_to_wis2box'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataingestionrecord',
            options={'verbose_name': 'Data Ingestion Record', 'verbose_name_plural': 'Data Ingestion Records'},
        ),
        migrations.AddConstraint(
            model_name='dataingestionrecord',
            constraint=models.UniqueConstraint(fields=('time', 'station'), name='unique_station_ingestion_record'),
        ),
    ]
