# Generated by Django 5.0.6 on 2024-10-23 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dataingestionrecord_hourly_aggregate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='plugin_unuploaded_check_interval',
            field=models.PositiveIntegerField(default=5, help_text='How often the plugin should check for records that have not been uploaded, in minutes. Allowed values between 5-30', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)], verbose_name='Unuploaded Records Check Interval in Minutes'),
        ),
    ]
