# Generated by Django 5.0.6 on 2024-10-24 11:06

import wis2box_adl.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_network_plugin_unuploaded_check_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='wmo_station_number',
            field=models.CharField(blank=True, help_text='WMO station number', max_length=255, null=True, validators=[wis2box_adl.core.utils.validate_as_integer], verbose_name='WMO Station Number'),
        ),
    ]
