# Generated by Django 5.0.6 on 2024-07-22 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dataingestionrecord_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='auto_processing_interval',
            field=models.PositiveIntegerField(default=15, help_text='Auto processing interval in minutes', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Auto Processing Interval'),
        ),
    ]
