# Generated by Django 5.0.6 on 2024-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_oscarsurfacestationlocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='plugin',
            field=models.CharField(help_text='Plugin to use for this network', max_length=255, verbose_name='Plugin'),
        ),
    ]
