# Generated by Django 5.0.6 on 2024-07-22 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_network_auto_processing_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='auto_processing_interval',
        ),
        migrations.AddField(
            model_name='network',
            name='plugin_processing_enabled',
            field=models.BooleanField(default=True, verbose_name='Plugin Auto Processing Enabled'),
        ),
        migrations.AddField(
            model_name='network',
            name='plugin_processing_interval',
            field=models.PositiveIntegerField(default=15, help_text='How often the plugin should run in minutes', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Plugin Auto Processing Interval in Minutes'),
        ),
    ]
