# Generated by Django 5.0.6 on 2024-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_network_auto_processing_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='plugin',
            field=models.CharField(default=2, help_text='Plugin to use for this network', max_length=255, unique=True, verbose_name='Plugin'),
            preserve_default=False,
        ),
    ]
