# Generated by Django 5.0.6 on 2024-07-24 10:34

import django.db.models.deletion
import wis2box_adl.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_network_plugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plugin Execution Event',
                'verbose_name_plural': 'Plugin Execution Events',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='adlsettings',
            options={'verbose_name': 'WIS2Box ADL Settings', 'verbose_name_plural': 'WIS2Box ADL Settings'},
        ),
        migrations.AlterModelOptions(
            name='dataingestionrecord',
            options={'ordering': ['-time'], 'verbose_name': 'Data Ingestion Record', 'verbose_name_plural': 'Data Ingestion Records'},
        ),
        migrations.AlterField(
            model_name='dataingestionrecord',
            name='file',
            field=models.FileField(upload_to=wis2box_adl.core.utils.get_station_directory_path, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='dataingestionrecord',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pluginexecutionevent'),
        ),
    ]
