# Generated by Django 5.0.6 on 2024-09-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pluginexecutionevent_alter_adlsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginexecutionevent',
            options={'ordering': ['finished_at'], 'verbose_name': 'Plugin Execution Event', 'verbose_name_plural': 'Plugin Execution Events'},
        ),
    ]
