# Generated by Django 5.0.6 on 2024-09-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_pluginexecutionevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='wmo_station_number',
            field=models.CharField(help_text='WMO station number', max_length=255, verbose_name='WMO Station Number'),
        ),
    ]
