# Generated by Django 5.0.6 on 2024-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_station_wmo_station_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='wmo_station_number',
            field=models.PositiveIntegerField(help_text='WMO station number', verbose_name='WMO Station Number'),
        ),
    ]
