# Generated by Django 5.1.9 on 2025-10-27 12:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0034_update_hourly_aggregate_with_circular_mean'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapViewerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Map Viewer Settings',
            },
        ),
        migrations.CreateModel(
            name='DataParameterStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scale', wagtail.fields.StreamField([('color_stop', 3)], blank=True, block_lookup={0: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Data value for this color', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hex color code (e.g., #FF0000)', 'max_length': 7, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional label for this value (e.g., 'Very Cold', 'Hot')", 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('value', 0), ('color', 1), ('label', 2)]], {})}, help_text='Define color stops for the gradient. Add values from low to high with corresponding colors.')),
                ('data_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='core.dataparameter')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_parameter_styles', to='viewer.mapviewersetting')),
            ],
            options={
                'verbose_name': 'Data Parameter Style',
                'verbose_name_plural': 'Data Parameter Styles',
                'unique_together': {('setting', 'data_parameter')},
            },
        ),
    ]
