# Generated by Django 5.1.9 on 2026-05-14 15:38

import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_dispatchchannel_options_and_more'),
        ('viewer', '0002_auto_add_mvt_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rotation_interval', models.PositiveIntegerField(default=10, help_text='Seconds to display each station before rotating')),
                ('poll_interval', models.PositiveIntegerField(default=5, help_text='Minutes between data refresh requests')),
                ('default_view', models.CharField(choices=[('rotating', 'Rotating Cards + Mini Map'), ('map', 'Full Map Overlay')], default='rotating', max_length=20)),
                ('parameters', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='widget_displays', to='core.dataparameter')),
                ('stations', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='widget_displays', to='core.stationlink')),
            ],
            options={
                'verbose_name': 'Widget Display',
                'verbose_name_plural': 'Widget Displays',
            },
        ),
    ]
