# backend environment variables, their defaults if left blank etc.
x-backend-variables: &backend-variables
  WAIT_HOSTS: adl_db:5432,adl_redis:6379
  WAIT_TIMEOUT: 120
  ADL_GUNICORN_NUM_OF_WORKERS: ${ADL_GUNICORN_NUM_OF_WORKERS:-4}
  ADL_GUNICORN_TIMEOUT: ${ADL_GUNICORN_TIMEOUT:-300}
  DEBUG: ${ADL_DEBUG:-False}
  WAGTAIL_SITE_NAME: ${ADL_SITE_NAME:-ADL}
  ADMIN_URL_PATH: ${ADL_ADMIN_URL_PATH:-adl-admin}
  TIME_ZONE: ${TIME_ZONE:-UTC}
  SECRET_KEY: ${SECRET_KEY:?}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
  DATABASE_URL: postgis://${ADL_DB_USER}:${ADL_DB_PASSWORD}@adl_db:5432/${ADL_DB_NAME}
  EMAIL_HOST: ${ADL_SMTP_EMAIL_HOST:-}
  EMAIL_PORT: ${ADL_SMTP_EMAIL_PORT:-}
  EMAIL_USE_TLS: ${ADL_SMTP_EMAIL_USE_TLS:-}
  EMAIL_HOST_USER: ${ADL_SMTP_EMAIL_HOST_USER:-}
  EMAIL_HOST_PASSWORD: ${ADL_SMTP_EMAIL_HOST_PASSWORD:-}
  DJANGO_ADMINS: ${ADL_ADMINS:-}
  WAGTAILADMIN_BASE_URL: ${CMS_BASE_URL:-}
  LANGUAGE_CODE: ${ADL_DEFAULT_LANGUAGE_CODE:-en}
  ADL_LOG_LEVEL: ${ADL_LOG_LEVEL:-WARN}
  ADL_DATABASE_LOG_LEVEL: ${ADL_DATABASE_LOG_LEVEL:-ERROR}
  ADL_CELERY_BEAT_DEBUG_LEVEL: ${ADL_CELERY_BEAT_DEBUG_LEVEL:-INFO}
  ADL_CELERY_WORKER_LOG_LEVEL: ${ADL_CELERY_WORKER_LOG_LEVEL:-INFO}
  MIGRATE_ON_STARTUP: ${MIGRATE_ON_STARTUP:-true}
  COLLECT_STATICFILES_ON_STARTUP: ${COLLECT_STATICFILES_ON_STARTUP:-true}
  REDIS_URL: redis://adl_redis:6379/0
  ADL_PLUGIN_DIR: ${ADL_PLUGIN_DIR:-/adl/plugins}
  ADL_PLUGIN_URLS: ${ADL_PLUGIN_URLS:-}
  ADL_PLUGIN_GIT_REPOS: ${ADL_PLUGIN_GIT_REPOS:-}
  ADL_PLUGIN_SETUP_ALREADY_RUN: ${ADL_PLUGIN_SETUP_ALREADY_RUN:-}
  ADL_DISABLE_PLUGIN_INSTALL_ON_STARTUP: ${ADL_DISABLE_PLUGIN_INSTALL_ON_STARTUP:-}

services:
  adl_db:
    container_name: adl_db
    image: timescale/timescaledb-ha:pg15
    restart: unless-stopped
    command: postgres -c max_connections=${POSTGRES_MAX_CONNECTIONS:-300} -c shared_buffers=${POSTGRES_SHARED_BUFFERS:-2GB}
    environment:
      - POSTGRES_USER=${ADL_DB_USER:-?}
      - POSTGRES_DB=${ADL_DB_NAME:-?}
      - POSTGRES_PASSWORD=${ADL_DB_PASSWORD:-?}
    ports:
      - "5432"
    volumes:
      - ${ADL_DB_VOLUME:-./docker/db_data/}:/home/postgres/pgdata/data

  adl_redis:
    image: redis:alpine
    container_name: adl_redis
    restart: unless-stopped

  adl:
    container_name: adl
    image: adl
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX=${DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX:-}
    restart: unless-stopped
    command: gunicorn wsgi
    environment:
      <<: *backend-variables
    expose:
      - "8000"
    depends_on:
      - adl_db
      - adl_redis
    ports:
      - "8000"
    volumes:
      - ${ADL_STATIC_VOLUME:-./docker/static}:/adl/app/src/adl/static
      - ${ADL_MEDIA_VOLUME:-./docker/media}:/adl/app/src/adl/media
      - ${ADL_BACKUP_VOLUME:-./docker/backup}:/adl/app/src/adl/backup

  adl_celery_worker:
    container_name: adl_celery_worker
    image: adl
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX=${DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX:-}
    restart: unless-stopped
    init: true
    command: celery-worker
    environment:
      <<: *backend-variables
      WAIT_HOSTS: adl_db:5432,adl_redis:6379,adl:8000
    depends_on:
      - adl_db
      - adl_redis
    volumes:
      - ${ADL_STATIC_VOLUME:-./docker/static}:/adl/app/src/adl/static
      - ${ADL_MEDIA_VOLUME:-./docker/media}:/adl/app/src/adl/media
      - ${ADL_BACKUP_VOLUME:-./docker/backup}:/adl/app/src/adl/backup

  adl_celery_beat:
    container_name: adl_celery_beat
    image: adl
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX=${DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX:-}
    restart: unless-stopped
    init: true
    command: celery-beat
    environment:
      <<: *backend-variables
      WAIT_HOSTS: adl_db:5432,adl_redis:6379,adl:8000
    depends_on:
      - adl_db
      - adl_redis
    volumes:
      - ${ADL_STATIC_VOLUME:-./docker/static}:/adl/app/src/adl/static
      - ${ADL_MEDIA_VOLUME:-./docker/media}:/adl/app/src/adl/media
      - ${ADL_BACKUP_VOLUME:-./docker/backup}:/adl/app/src/adl/backup

  adl_web_proxy:
    container_name: adl_web_proxy
    image: nginx:1.20.2-alpine
    restart: unless-stopped
    volumes:
      - ${ADL_STATIC_VOLUME:-./docker/static}:/wagtail_static
      - ${ADL_MEDIA_VOLUME:-./docker/media}:/wagtail_media
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${ADL_WEB_PROXY_PORT:-80}:80

networks:
  default:
    external: true
    name: ${ADL_NETWORK_NAME:-adl}