# Generated by Django 5.0.6 on 2024-06-28 06:56

from django.db import migrations

from core.utils import create_default_data_parameters


def add_default_data_parameters(apps, schema_editor):
    create_default_data_parameters()


def backwards(apps, schema_editor):
    """nothing to do"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_data_parameters, backwards),
    ]
