# Generated by Django 5.0.6 on 2024-11-28 17:44

import adl.core.utils
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import modelcluster.fields
import timescale.db.models.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the variable', max_length=255, verbose_name='Name')),
                ('parameter', models.CharField(choices=adl.core.utils.get_data_parameters_as_choices, max_length=255, unique=True, verbose_name='Parameter')),
                ('unit', models.CharField(help_text='Unit of the variable', max_length=255, verbose_name='Unit')),
                ('description', models.TextField(help_text='Description of the variable', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the network', max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('automatic', 'Automatic Weather Stations'), ('manual', 'Manual Weather Stations')], help_text='Weather station type', max_length=255, verbose_name='Weather Stations Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
            },
        ),
        migrations.CreateModel(
            name='OscarSurfaceStationLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the station', max_length=255, verbose_name='Name')),
                ('wigos_id', models.CharField(help_text='WIGOS ID of the station', max_length=255, unique=True, verbose_name='WIGOS ID')),
                ('latitude', models.FloatField(help_text='Latitude of the station', verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude of the station', verbose_name='Longitude')),
                ('elevation', models.FloatField(help_text='Elevation of the station', verbose_name='Elevation')),
            ],
        ),
        migrations.CreateModel(
            name='PluginExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plugin Execution Event',
                'verbose_name_plural': 'Plugin Execution Events',
                'ordering': ['finished_at'],
            },
        ),
        migrations.CreateModel(
            name='AdlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'WIS2Box ADL Settings',
                'verbose_name_plural': 'WIS2Box ADL Settings',
            },
        ),
        migrations.CreateModel(
            name='Wis2BoxUpload',
            fields=[
                ('dispatchchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.dispatchchannel')),
                ('storage_endpoint', models.CharField(max_length=255, verbose_name='Storage Endpoint')),
                ('storage_username', models.CharField(max_length=255, verbose_name='Storage Username')),
                ('storage_password', models.CharField(max_length=255, verbose_name='Storage Password')),
                ('dataset_id', models.CharField(max_length=255, verbose_name='Dataset ID')),
                ('wis2box_hourly_aggregate', models.BooleanField(default=True, help_text='Check this if you want only one record per hour to be uploaded to wis2box', verbose_name='Enable WIS2BOX Hourly Aggregation')),
                ('wis2box_hourly_aggregate_strategy', models.CharField(blank=True, choices=[('latest', 'Latest in the Hour')], default='latest', help_text='Method to use for aggregating hourly data for ingestion to WIS2BOX', max_length=255, null=True, verbose_name='WIS2BOX Hourly Aggregate Strategy')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.dispatchchannel',),
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(help_text='Plugin to use for this network', max_length=255, verbose_name='Plugin')),
                ('plugin_processing_enabled', models.BooleanField(default=True, help_text='If unchecked, the plugin will not run automatically', verbose_name='Plugin Auto Processing Enabled')),
                ('plugin_processing_interval', models.PositiveIntegerField(default=15, help_text='How often the plugin should run, in minutes', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Plugin Auto Processing Interval in Minutes')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.network', verbose_name='Network')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Network Connection',
                'verbose_name_plural': 'Network Connections',
            },
        ),
        migrations.CreateModel(
            name='NetworkDispatchChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispatchchannel')),
                ('connection', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_channels', to='core.networkconnection')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='Unique Station Identifier', max_length=255, verbose_name='Station ID')),
                ('name', models.CharField(help_text='Name of the station', max_length=255, verbose_name='Name')),
                ('wsi_series', models.PositiveIntegerField(help_text='WIGOS identifier series', verbose_name='WSI Series')),
                ('wsi_issuer', models.PositiveIntegerField(help_text='WIGOS issuer of identifier', verbose_name='WSI Issuer')),
                ('wsi_issue_number', models.PositiveIntegerField(help_text='WIGOS issue number', verbose_name='WSI Issue Number')),
                ('wsi_local', models.CharField(help_text='WIGOS local identifier', max_length=255, verbose_name='WSI Local')),
                ('wmo_block_number', models.PositiveIntegerField(blank=True, default=None, help_text='WMO block number', null=True, verbose_name='WMO Block Number')),
                ('wmo_station_number', models.CharField(blank=True, help_text='WMO station number', max_length=255, null=True, validators=[adl.core.utils.validate_as_integer], verbose_name='WMO Station Number')),
                ('station_type', models.PositiveIntegerField(choices=[(0, 'Automatic'), (1, 'Manned'), (2, 'Hybrid: both automatic and manned')], help_text='Type of observing station, encoding using code table 0 02 001 (set to 0, automatic)', verbose_name='Station Type')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Location of the station', srid=4326, verbose_name='Location')),
                ('station_height_above_msl', models.FloatField(blank=True, help_text='Height of the station ground above mean sea level (to 1 decimal place)', null=True, verbose_name='Station Height Above MSL')),
                ('thermometer_height', models.FloatField(blank=True, help_text='Height of thermometer or temperature sensor above the local ground to 2 decimal places', null=True, verbose_name='Thermometer Height')),
                ('barometer_height_above_msl', models.FloatField(blank=True, help_text='Height of the barometer above mean sea level (to 1 decimal place), typically height of station ground plus the height of the sensor above local ground', null=True, verbose_name='Barometer Height Above MSL')),
                ('anemometer_height', models.FloatField(blank=True, help_text='Height of the anemometer above local ground to 2 decimal places', null=True, verbose_name='Anemometer Height')),
                ('rain_sensor_height', models.FloatField(blank=True, help_text='Height of the rain gauge above local ground to 2 decimal place', null=True, verbose_name='Rain Sensor Height')),
                ('method_of_ground_state_measurement', models.PositiveIntegerField(blank=True, choices=[(0, 'Manual observation'), (1, 'Video camera method'), (2, 'Infrared method'), (3, 'Laser method'), (14, 'Others'), (15, 'Missing value')], help_text='Method of observing the snow depth encoded using code table 0 02 177', null=True, verbose_name='Method of Ground State Measurement')),
                ('method_of_snow_depth_measurement', models.PositiveIntegerField(blank=True, help_text='Method of observing the snow depth encoded using code table 0 02 177', null=True, verbose_name='Method of Snow Depth Measurement')),
                ('time_period_of_wind', models.PositiveIntegerField(blank=True, help_text='Time period over which the wind speed and direction have been averaged. 10 minutes in normal cases or the number of minutes since a significant change occuring in the preceeding 10 minutes.', null=True, verbose_name='Time Period of Wind')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Station Timezone')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.network', verbose_name='Network')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='DataIngestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=adl.core.utils.get_station_directory_path, verbose_name='File')),
                ('uploaded_to_wis2box', models.BooleanField(default=False, verbose_name='Uploaded to WIS2BOX')),
                ('is_hourly_aggregate', models.BooleanField(default=False, verbose_name='Is Hourly Aggregate')),
                ('hourly_aggregate_file', models.FileField(blank=True, null=True, upload_to=adl.core.utils.get_station_directory_path)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pluginexecutionevent')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Data Ingestion Record',
                'verbose_name_plural': 'Data Ingestion Records',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='StationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_links', to='core.networkconnection', verbose_name='Network Connection')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station')),
            ],
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('station_id', 'network'), name='unique_station_id_network'),
        ),
        migrations.AddConstraint(
            model_name='dataingestionrecord',
            constraint=models.UniqueConstraint(fields=('time', 'station'), name='unique_station_ingestion_record'),
        ),
        migrations.AlterUniqueTogether(
            name='stationlink',
            unique_together={('network_connection', 'station')},
        ),
    ]
