# Generated by Django 5.0.6 on 2024-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_networkconnection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconnection',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
