# Generated by Django 5.1.4 on 2025-01-12 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_observationrecord_unique_station_param_obs_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchchannel',
            name='last_upload_obs_time',
        ),
        migrations.CreateModel(
            name='StationChannelDispatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_sent_obs_time', models.DateTimeField(blank=True, null=True, verbose_name='Last Send Observation Time')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispatchchannel', verbose_name='Channel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Station Channel Dispatch Status',
                'verbose_name_plural': 'Station Channel Dispatch Status',
                'constraints': [models.UniqueConstraint(fields=('channel', 'station'), name='unique_channel_station_dispatch_status')],
            },
        ),
    ]
