# Generated by Django 5.1.4 on 2025-01-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dispatchchannel_last_upload_obs_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlsettings',
            name='aggregate_from_date',
            field=models.DateTimeField(blank=True, help_text='Date to start aggregation from. Leave empty to use the current date and time', null=True, verbose_name='Aggregate Start Date'),
        ),
    ]
