# Generated by Django 5.0.6 on 2024-11-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_observationrecord_delete_dataingestionrecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wis2boxupload',
            options={'verbose_name': 'WIS2BOX Upload', 'verbose_name_plural': 'WIS2BOX Uploads'},
        ),
        migrations.AddField(
            model_name='observationrecord',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.networkconnection', verbose_name='Network Connection'),
            preserve_default=False,
        ),
    ]
