# Generated by Django 5.1.4 on 2025-01-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_station_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaggregatedobservationrecord',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregated_observation_records', to='core.networkconnection', verbose_name='Network Connection'),
        ),
        migrations.AlterField(
            model_name='hourlyaggregatedobservationrecord',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_aggregated_observation_records', to='core.networkconnection', verbose_name='Network Connection'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_records', to='core.networkconnection', verbose_name='Network Connection'),
        ),
    ]
