# Generated by Django 5.0.6 on 2024-11-29 13:04

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_wis2boxupload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchchannel',
            name='data_check_interval',
            field=models.PositiveIntegerField(default=10, help_text='How often the channel should check the database for new data, in minutes', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Data Check Interval in Minutes'),
        ),
        migrations.CreateModel(
            name='DispatchChannelParameterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('channel_parameter', models.CharField(help_text='Parameter name in the channel', max_length=255, verbose_name='Channel Parameter')),
                ('dispatch_channel', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_mappings', to='core.dispatchchannel')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter')),
            ],
            options={
                'unique_together': {('dispatch_channel', 'parameter')},
            },
        ),
    ]
