# Generated by Django 5.1.4 on 2025-01-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_adlsettings_aggregate_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adlsettings',
            name='hourly_aggregation_interval',
        ),
    ]
