# Generated by Django 5.0.6 on 2024-11-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dispatchchannel_data_check_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchchannel',
            name='last_upload_obs_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Upload's Observation Time"),
        ),
    ]
