# Generated by Django 5.1.4 on 2025-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_adlsettings_hourly_aggregation_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationlink',
            name='enabled',
            field=models.BooleanField(default=True, help_text='If unchecked, this station  will not be processed', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='stationlink',
            name='aggregate_from_date',
            field=models.DateTimeField(blank=True, help_text='Date to start aggregation from. Leave empty to use the current date and time', null=True, verbose_name='Aggregation Start Date'),
        ),
    ]
