# Generated by Django 5.0.6 on 2025-01-06 10:38

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dispatchchannel_last_upload_obs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationrecord',
            name='is_daily',
            field=models.BooleanField(default=False, verbose_name='Is Daily'),
        ),
        migrations.CreateModel(
            name='DailyAggregatedObservationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('min_value', models.FloatField(verbose_name='Min Value')),
                ('max_value', models.FloatField(verbose_name='Max Value')),
                ('avg_value', models.FloatField(verbose_name='Avg Value')),
                ('sum_value', models.FloatField(verbose_name='Sum Value')),
                ('records_count', models.PositiveIntegerField(verbose_name='Records Count')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.networkconnection', verbose_name='Network Connection')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HourlyAggregatedObservationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('min_value', models.FloatField(verbose_name='Min Value')),
                ('max_value', models.FloatField(verbose_name='Max Value')),
                ('avg_value', models.FloatField(verbose_name='Avg Value')),
                ('sum_value', models.FloatField(verbose_name='Sum Value')),
                ('records_count', models.PositiveIntegerField(verbose_name='Records Count')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.networkconnection', verbose_name='Network Connection')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
