# Generated by Django 5.0.6 on 2025-01-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_observationrecord_is_daily_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wis2boxupload',
            name='wis2box_hourly_aggregate',
        ),
        migrations.RemoveField(
            model_name='wis2boxupload',
            name='wis2box_hourly_aggregate_strategy',
        ),
        migrations.AddField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_measure',
            field=models.CharField(blank=True, choices=[('min', 'Minimum Value'), ('max', 'Maximum Value'), ('avg', 'Average'), ('sum', 'Sum'), ('count', 'Records Count')], max_length=255, null=True, verbose_name='Aggregation Measure'),
        ),
        migrations.AddField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_period',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=255, null=True, verbose_name='Aggregation Period'),
        ),
        migrations.AddField(
            model_name='dispatchchannelparametermapping',
            name='use_aggregated_data',
            field=models.BooleanField(default=False, verbose_name='Use Aggregated Data'),
        ),
    ]
