# Generated by Django 5.1.4 on 2025-02-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_stationlink_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationchanneldispatchstatus',
            options={'ordering': ['-last_sent_obs_time'], 'verbose_name': 'Station Channel Dispatch Status', 'verbose_name_plural': 'Station Channel Dispatch Status'},
        ),
        migrations.AlterField(
            model_name='stationchanneldispatchstatus',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_statuses', to='core.dispatchchannel', verbose_name='Channel'),
        ),
    ]
