# Generated by Django 5.0.6 on 2025-01-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_wis2boxupload_wis2box_hourly_aggregate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_measure',
            field=models.CharField(blank=True, choices=[('min', 'Minimum Value'), ('max', 'Maximum Value'), ('avg', 'Average'), ('sum', 'Sum'), ('count', 'Records Count')], default='avg', max_length=255, null=True, verbose_name='Aggregation Measure'),
        ),
        migrations.AlterField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_period',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='hourly', max_length=255, null=True, verbose_name='Aggregation Period'),
        ),
    ]
