# Generated by Django 5.1.4 on 2025-02-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_stationchanneldispatchstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchchannel',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starting date for the data to dispatch. Leave blank to use the whole data period'),
        ),
    ]
