# Generated by Django 5.0.6 on 2025-01-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_dispatchchannelparametermapping_aggregation_measure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_measure',
        ),
        migrations.RemoveField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_period',
        ),
        migrations.RemoveField(
            model_name='dispatchchannelparametermapping',
            name='use_aggregated_data',
        ),
        migrations.AddField(
            model_name='dispatchchannel',
            name='aggregation_period',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='hourly', max_length=255, null=True, verbose_name='Aggregation Period'),
        ),
        migrations.AddField(
            model_name='dispatchchannel',
            name='use_aggregated_data',
            field=models.BooleanField(default=False, verbose_name='Use Aggregated Data'),
        ),
    ]
