# Generated by Django 5.1.4 on 2025-02-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dispatchchannel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchchannel',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank to use the whole data period', null=True, verbose_name='Starting date for the data to dispatch'),
        ),
    ]
