# Generated by Django 5.0.6 on 2025-01-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_dispatchchannelparametermapping_aggregation_measure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchchannel',
            name='use_aggregated_data',
        ),
        migrations.AddField(
            model_name='dispatchchannel',
            name='send_aggregated_data',
            field=models.BooleanField(default=False, verbose_name='Send Aggregated Data'),
        ),
    ]
