# Generated by Django 5.1.4 on 2025-02-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dispatchchannel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchchannel',
            name='public_url',
            field=models.URLField(blank=True, help_text='Public URL of the channel,if available', null=True, verbose_name='Public URL'),
        ),
    ]
