# Generated by Django 5.1.4 on 2025-03-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dispatchchannel_public_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconnection',
            name='plugin_processing_enabled',
            field=models.BooleanField(default=True, help_text='If unchecked, the plugin will NOT run automatically', verbose_name='Active'),
        ),
    ]
