# Generated by Django 5.0.6 on 2025-01-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_dispatchchannel_use_aggregated_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlsettings',
            name='daily_aggregation_time',
            field=models.TimeField(default='00:00', verbose_name='Daily Aggregation Time'),
        ),
        migrations.AddField(
            model_name='adlsettings',
            name='hourly_aggregation_interval',
            field=models.PositiveIntegerField(default=10, verbose_name='Hourly Aggregation Interval in Minutes'),
        ),
    ]
