# Generated by Django 5.1.4 on 2025-04-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_networkconnection_plugin_processing_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataparameter',
            options={'ordering': ['name'], 'verbose_name': 'Data Parameter', 'verbose_name_plural': 'Data Parameters'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
