# Generated by Django 5.0.6 on 2025-01-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adlsettings_daily_aggregation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_measure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aggregation Measure'),
        ),
    ]
