# Generated by Django 5.1.4 on 2025-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dataparameter_options_alter_unit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataparameter',
            name='category',
            field=models.CharField(choices=[('meteorological', 'Meteorological'), ('environmental', 'Environmental'), ('health', 'Station Health'), ('communication', 'Communication')], default='meteorological', help_text='Type of parameter', max_length=50, verbose_name='Category'),
        ),
    ]
