# Generated by Django 5.0.6 on 2025-01-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dispatchchannelparametermapping_aggregation_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_measure',
            field=models.CharField(choices=[('avg', 'Average Value'), ('sum', 'Sum Value'), ('min', 'Minimum Value'), ('max', 'Maximum Value')], default='avg_value', max_length=255, verbose_name='Aggregation Measure'),
        ),
    ]
