# Generated by Django 5.0.6 on 2025-01-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_dispatchchannelparametermapping_aggregation_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDispatchedRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_record_id', models.BigIntegerField(verbose_name='Observation Record ID')),
                ('dispatch_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispatchchannel', verbose_name='Dispatch Channel')),
            ],
        ),
    ]
