# Generated by Django 5.1.9 on 2025-07-22 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dataparameter_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconnection',
            name='plugin_processing_interval',
            field=models.PositiveIntegerField(default=15, help_text='How often the plugin should run, in minutes', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Interval'),
        ),
    ]
