# Generated by Django 5.1.9 on 2025-08-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_networkconnection_plugin_processing_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkconnection',
            name='batch_size',
            field=models.PositiveIntegerField(default=10, help_text='Number of stations to process in a single batch', verbose_name='Processing Batch Size'),
        ),
    ]
