# Generated by Django 5.0.6 on 2025-01-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_channeldispatchedrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchchannelparametermapping',
            name='aggregation_measure',
            field=models.CharField(choices=[('avg_value', 'Average Value'), ('sum_value', 'Sum Value'), ('min_value', 'Minimum Value'), ('max_value', 'Maximum Value')], default='avg_value', max_length=255, verbose_name='Aggregation Measure'),
        ),
    ]
