# Generated by Django 5.1.9 on 2025-08-11 10:20

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_networkconnection_batch_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='timezone',
        ),
        migrations.AddField(
            model_name='stationlink',
            name='timezone_info',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Station Timezone'),
        ),
    ]
