# Generated by Django 5.0.6 on 2025-01-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_dispatchchannelparametermapping_aggregation_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='wis2boxupload',
            name='secure',
            field=models.BooleanField(default=False, help_text='If checked, HTTPS connection will be used,otherwise HTTP', verbose_name='Use Secure Connection'),
        ),
    ]
