# Generated by Django 5.1.9 on 2025-08-12 13:17

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_station_timezone_stationlink_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkconnection',
            name='stations_timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text='Default Timezone of the stations in this network connection', verbose_name='Stations Timezone'),
        ),
        migrations.AddField(
            model_name='stationlink',
            name='use_connection_timezone',
            field=models.BooleanField(default=True, help_text="If checked, the station will use the timezone from the network connection. If unchecked, it will use the station's set timezone that will be appear below", verbose_name='Use Connection Timezone'),
        ),
    ]
