# Generated by Django 5.1.9 on 2025-08-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_obs_agg_1h'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyObsAgg',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('bucket', models.DateTimeField()),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
                ('avg_value', models.FloatField(null=True)),
                ('sum_value', models.FloatField(null=True)),
                ('records_count', models.IntegerField()),
            ],
            options={
                'db_table': 'obs_agg_1h_v',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='hourlyaggregatedobservationrecord',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='hourlyaggregatedobservationrecord',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='hourlyaggregatedobservationrecord',
            name='station',
        ),
        migrations.DeleteModel(
            name='DailyAggregatedObservationRecord',
        ),
        migrations.DeleteModel(
            name='HourlyAggregatedObservationRecord',
        ),
    ]
