# Generated by Django 5.1.9 on 2025-08-14 07:14

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_hourlyobsagg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlyobsagg',
            options={'managed': False, 'ordering': ['-bucket', 'station']},
        ),
        migrations.AlterField(
            model_name='dispatchchannel',
            name='aggregation_period',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly')], default='hourly', max_length=255, null=True, verbose_name='Aggregation Period'),
        ),
        migrations.CreateModel(
            name='DispatchChannelStationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('dispatch_channel', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_links', to='core.dispatchchannel')),
                ('station_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_channel_links', to='core.stationlink', verbose_name='Station Link')),
            ],
            options={
                'unique_together': {('dispatch_channel', 'station_link')},
            },
        ),
    ]
