# Generated by Django 5.1.9 on 2025-09-24 11:55

from django.db import migrations, models
from django.utils import timezone


def set_initial_modified_at(apps, schema_editor):
    DataParameter = apps.get_model('core', 'DataParameter')
    # Set all existing records to current time
    DataParameter.objects.update(modified_at=timezone.now())


def reverse_set_initial_modified_at(apps, schema_editor):
    # Nothing needed for reverse
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_dataparameter_qc_checks_observationrecord_qc_bits_and_more'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='dataparameter',
            name='modified_at',
            field=models.DateTimeField(null=True),  # Temporarily allow null
        ),
        migrations.RunPython(set_initial_modified_at, reverse_set_initial_modified_at),
        migrations.AlterField(
            model_name='dataparameter',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),  # Now make it non-null
        ),
    ]
