# Generated by Django 5.1.9 on 2025-09-24 14:30

from django.db import migrations, models

from django.utils import timezone


def set_initial_modified_at(apps, schema_editor):
    StationLink = apps.get_model('core', 'StationLink')
    # Set all existing records to current time
    StationLink.objects.update(modified_at=timezone.now())


def reverse_set_initial_modified_at(apps, schema_editor):
    # Nothing needed for reverse
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_alter_dataparameter_qc_checks'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='stationlink',
            name='modified_at',
            field=models.DateTimeField(null=True),  # Temporarily allow null
        ),
        migrations.RunPython(set_initial_modified_at, reverse_set_initial_modified_at),
        migrations.AlterField(
            model_name='stationlink',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),  # Now make it non-null
        ),
    
    ]
