# Generated by Django 5.1.9 on 2025-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_stationlink_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchchannel',
            name='network_connections',
            field=models.ManyToManyField(blank=True, related_name='dispatch_channels_new', to='core.networkconnection', verbose_name='Network Connections'),
        ),
    ]
