# Generated by Django 5.1.9 on 2025-09-25 16:21

from django.db import migrations


def migrate_network_connections(apps, schema_editor):
    DispatchChannel = apps.get_model('core', 'DispatchChannel')
    
    for channel in DispatchChannel.objects.all():
        if channel.network_connection:
            channel.network_connections.add(channel.network_connection)


def reverse_migrate_network_connections(apps, schema_editor):
    DispatchChannel = apps.get_model('core', 'DispatchChannel')
    
    for channel in DispatchChannel.objects.all():
        first_connection = channel.network_connections.first()
        if first_connection:
            channel.network_connection = first_connection
            channel.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_dispatchchannel_network_connections'),
    ]
    
    operations = [
        migrations.RunPython(
            migrate_network_connections,
            reverse_migrate_network_connections
        ),
    ]
