# Generated by Django 5.1.9 on 2025-09-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_auto_20250925_1621'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='dispatchchannel',
            name='network_connection',
        ),
        migrations.AlterField(
            model_name='dispatchchannel',
            name='network_connections',
            field=models.ManyToManyField(related_name='dispatch_channels', to='core.networkconnection',
                                         verbose_name='Network Connections'),
        ),
    ]
