# Generated by Django 5.1.9 on 2025-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_dispatchchannel_network_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataparameter',
            name='aggregation_method',
            field=models.CharField(choices=[('standard', 'Standard (Min/Max/Avg/Sum)'), ('circular', 'Circular Mean (for angular data like wind direction)')], default='standard', help_text="How to aggregate this parameter in hourly/daily summaries. Use 'Circular Mean' for angular measurements like wind direction.", max_length=20, verbose_name='Aggregation Method'),
        ),
    ]
