# Generated by Django 5.1.9 on 2025-11-12 13:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_update_hourly_aggregate_with_circular_mean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchchannelstationlink',
            name='dispatch_channel',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_station_links', to='core.dispatchchannel'),
        ),
    ]
