# Generated by Django 5.1.9 on 2025-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_dispatchchannelstationlink_dispatch_channel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='observationrecord',
            index=models.Index(fields=['station', '-time'], name='core_observ_station_629c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='observationrecord',
            index=models.Index(fields=['connection', 'station', '-time'], name='core_observ_connect_143241_idx'),
        ),
    ]
