# Generated by Django 5.1.9 on 2025-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_observationrecord_core_observ_station_629c1b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchchannel',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='networkconnection',
            options={'ordering': ['sort_order'], 'verbose_name': 'Network Connection', 'verbose_name_plural': 'Network Connections'},
        ),
        migrations.AddField(
            model_name='dispatchchannel',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which the connections are displayed', verbose_name='Sort Order'),
        ),
        migrations.AddField(
            model_name='networkconnection',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which the connections are displayed', verbose_name='Sort Order'),
        ),
    ]
