# Generated by Django 5.1.9 on 2026-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_dispatchchannel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataparameter',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon displayed alongside this parameter in dashboards and widgets', max_length=100, verbose_name='Icon'),
        ),
    ]
