# Generated by Django 5.1.9 on 2026-05-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_dataparameter_icon'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlsettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Displayed in the footer of widget display pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='adlsettings',
            name='organisation_name',
            field=models.CharField(blank=True, default='', help_text='Displayed in the footer of widget display pages', max_length=255, verbose_name='Organisation Name'),
        ),
    ]
