# Generated by Django 6.0.5 on 2026-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_create_dimensionless_wmo_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataparameter',
            name='name',
            field=models.CharField(help_text='Name of the variable', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
