# Generated by Django 6.0.7 on 2026-07-13 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_dataparameter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchchannel',
            name='dispatch_timeout_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Maximum time a single station dispatch may run before it is terminated', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1800)], verbose_name='Dispatch Timeout in Seconds'),
        ),
    ]
