# Generated by Django 6.0.7 on 2026-07-13 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_dispatchchannel_dispatch_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchchannel',
            name='max_records_per_dispatch',
            field=models.PositiveIntegerField(default=500, help_text='Maximum number of records (observation times) sent per station in a single dispatch run. A backlog is drained incrementally across runs', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Maximum Records per Dispatch'),
        ),
    ]
