# Generated by Django 6.0.7 on 2026-07-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_dispatchchannel_max_records_per_dispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchChannelHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(verbose_name='Last Run At')),
                ('stations_spawned', models.PositiveIntegerField(default=0, verbose_name='Stations Spawned')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat', to='core.dispatchchannel', verbose_name='Channel')),
            ],
        ),
    ]
