# Generated by Django 6.0.7 on 2026-07-30 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_move_dispatch_periodic_tasks_to_dispatch_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConnectionHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(verbose_name='Last Run At')),
                ('station_links_enabled', models.PositiveIntegerField(default=0, verbose_name='Station Links Enabled')),
                ('batches_spawned', models.PositiveIntegerField(default=0, verbose_name='Batches Spawned')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Task ID')),
                ('last_manual_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Manual Run At')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat', to='core.networkconnection', verbose_name='Connection')),
            ],
            options={
                'verbose_name': 'Network Connection Heartbeat',
                'verbose_name_plural': 'Network Connection Heartbeats',
            },
        ),
    ]
