# Generated by Django 6.0.7 on 2026-07-30 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_networkconnectionheartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkconnection',
            name='ingest_timeout_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Maximum time ingesting a single station may run before it is terminated', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1800)], verbose_name='Ingestion Timeout in Seconds'),
        ),
    ]
