# Generated by Django 6.0.7 on 2026-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_networkconnection_ingest_timeout_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconnectionheartbeat',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Run At'),
        ),
    ]
