# Generated by Django 6.0.7 on 2026-07-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_networkconnectionheartbeat_last_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkconnectionheartbeat',
            name='worker_versions',
            field=models.JSONField(blank=True, null=True, verbose_name='Worker Library Versions'),
        ),
    ]
