# Generated by Django 6.0.7 on 2026-08-03 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_networkconnectionheartbeat_worker_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconnection',
            name='ingest_timeout_seconds',
            field=models.PositiveIntegerField(default=300, help_text="Time budgeted per station. Stations are ingested in batches, so this is not enforced on each station individually — it sets the batch's time limit, and a slow station can consume another's share. See the effective figure below.", validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1800)], verbose_name='Ingestion Timeout in Seconds'),
        ),
    ]
