# Generated by Django 5.1.9 on 2025-08-06 19:46

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_networkconnection_batch_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationLinkActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('direction', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push')], max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('records_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('messages_count', models.PositiveIntegerField(default=0)),
                ('station_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stationlink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
