# Generated by Django 5.1.9 on 2025-08-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_networkconnection_stations_timezone_and_more'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationlinkactivitylog',
            name='dispatch_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.dispatchchannel'),
        ),
        migrations.AddField(
            model_name='stationlinkactivitylog',
            name='obs_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Observation End Time'),
        ),
        migrations.AddField(
            model_name='stationlinkactivitylog',
            name='obs_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Observation Start Time'),
        ),
    ]
