# Generated by Django 5.1.9 on 2025-08-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_networkconnection_stations_timezone_and_more'),
        ('monitoring', '0002_stationlinkactivitylog_dispatch_channel_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stationlinkactivitylog',
            index=models.Index(fields=['station_link', 'time'], name='sta_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stationlinkactivitylog',
            index=models.Index(fields=['station_link', 'direction', 'time'], name='sta_station_dir_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stationlinkactivitylog',
            index=models.Index(condition=models.Q(('success', False)), fields=['time'], name='sta_failed_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stationlinkactivitylog',
            index=models.Index(fields=['dispatch_channel', 'time'], name='sta_channel_time_idx'),
        ),
    ]
