# Generated by Django 5.1.9 on 2025-11-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_stationlinkactivitylog_sta_station_time_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationlinkactivitylog',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='STARTED', max_length=50),
        ),
    ]
