# Generated by Django 6.0.7 on 2026-07-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_stationlinkactivitylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationlinkactivitylog',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='STARTED', max_length=50),
        ),
    ]
