# Generated by Django 6.0.7 on 2026-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_stationlinkactivitylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationlinkactivitylog',
            name='sources_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
