# Generated by Django 6.0.7 on 2026-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_stationlinkactivitylog_sources_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationlinkactivitylog',
            name='error_category',
            field=models.CharField(blank=True, choices=[('DNS_FAILURE', 'DNS_FAILURE'), ('TCP_REFUSED', 'TCP_REFUSED'), ('TCP_TIMEOUT', 'TCP_TIMEOUT'), ('TLS_FAILURE', 'TLS_FAILURE'), ('AUTH_FAILED', 'AUTH_FAILED'), ('PERMISSION_DENIED', 'PERMISSION_DENIED'), ('PATH_NOT_FOUND', 'PATH_NOT_FOUND'), ('PROTOCOL_ERROR', 'PROTOCOL_ERROR'), ('UNKNOWN', 'UNKNOWN')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stationlinkactivitylog',
            name='error_layer',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationlinkactivitylog',
            name='exception_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
