# Generated by Django 6.0.7 on 2026-07-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_networkconnection_ingest_timeout_seconds'),
        ('monitoring', '0007_stationlinkactivitylog_error_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConnectionHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('STALE', 'Stale'), ('UNSUPPORTED', 'Unsupported'), ('DISABLED', 'Disabled'), ('MISCONFIGURED', 'Misconfigured')], max_length=20, verbose_name='Status')),
                ('first_failing_layer', models.CharField(blank=True, max_length=32, null=True, verbose_name='First Failing Layer')),
                ('headline_check_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Headline Check')),
                ('headline_message', models.TextField(blank=True, default='', verbose_name='Headline Message')),
                ('since', models.DateTimeField(verbose_name='Since')),
                ('evaluated_at', models.DateTimeField(verbose_name='Evaluated At')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='core.networkconnection', verbose_name='Connection')),
            ],
            options={
                'verbose_name': 'Network Connection Health',
                'verbose_name_plural': 'Network Connection Health',
            },
        ),
        migrations.CreateModel(
            name='NetworkConnectionHealthTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(verbose_name='At')),
                ('from_status', models.CharField(blank=True, choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('STALE', 'Stale'), ('UNSUPPORTED', 'Unsupported'), ('DISABLED', 'Disabled'), ('MISCONFIGURED', 'Misconfigured')], max_length=20, null=True, verbose_name='From Status')),
                ('from_first_failing_layer', models.CharField(blank=True, max_length=32, null=True, verbose_name='From First Failing Layer')),
                ('to_status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('STALE', 'Stale'), ('UNSUPPORTED', 'Unsupported'), ('DISABLED', 'Disabled'), ('MISCONFIGURED', 'Misconfigured')], max_length=20, verbose_name='To Status')),
                ('to_first_failing_layer', models.CharField(blank=True, max_length=32, null=True, verbose_name='To First Failing Layer')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_transitions', to='core.networkconnection', verbose_name='Connection')),
            ],
            options={
                'verbose_name': 'Network Connection Health Transition',
                'verbose_name_plural': 'Network Connection Health Transitions',
                'indexes': [models.Index(fields=['connection', 'at'], name='health_trans_conn_at_idx')],
            },
        ),
    ]
