# Generated by Django 6.0.7 on 2026-07-31 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_networkconnection_ingest_timeout_seconds'),
        ('monitoring', '0008_networkconnectionhealth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProbeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=32, verbose_name='Check')),
                ('layer', models.CharField(max_length=32, verbose_name='Layer')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('category', models.CharField(blank=True, choices=[('DNS_FAILURE', 'DNS_FAILURE'), ('TCP_REFUSED', 'TCP_REFUSED'), ('TCP_TIMEOUT', 'TCP_TIMEOUT'), ('TLS_FAILURE', 'TLS_FAILURE'), ('AUTH_FAILED', 'AUTH_FAILED'), ('PERMISSION_DENIED', 'PERMISSION_DENIED'), ('PATH_NOT_FOUND', 'PATH_NOT_FOUND'), ('PROTOCOL_ERROR', 'PROTOCOL_ERROR'), ('UNKNOWN', 'UNKNOWN')], max_length=50, null=True, verbose_name='Category')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Latency (ms)')),
                ('at', models.DateTimeField(verbose_name='At')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_probe_results', to='core.networkconnection', verbose_name='Connection')),
                ('station_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_probe_results', to='core.stationlink', verbose_name='Station Link')),
            ],
            options={
                'verbose_name': 'Source Probe Result',
                'verbose_name_plural': 'Source Probe Results',
                'indexes': [models.Index(fields=['connection', 'check_id', 'at'], name='probe_conn_check_at_idx')],
            },
        ),
    ]
