# Generated by Django 6.0.7 on 2026-08-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_redact_stored_secrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconnectionhealth',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('STALE', 'Stale'), ('UNSUPPORTED', 'Unsupported'), ('NOT_APPLICABLE', 'Not applicable'), ('DISABLED', 'Disabled'), ('MISCONFIGURED', 'Misconfigured')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='networkconnectionhealthtransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('STALE', 'Stale'), ('UNSUPPORTED', 'Unsupported'), ('NOT_APPLICABLE', 'Not applicable'), ('DISABLED', 'Disabled'), ('MISCONFIGURED', 'Misconfigured')], max_length=20, null=True, verbose_name='From Status'),
        ),
        migrations.AlterField(
            model_name='networkconnectionhealthtransition',
            name='to_status',
            field=models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('STALE', 'Stale'), ('UNSUPPORTED', 'Unsupported'), ('NOT_APPLICABLE', 'Not applicable'), ('DISABLED', 'Disabled'), ('MISCONFIGURED', 'Misconfigured')], max_length=20, verbose_name='To Status'),
        ),
    ]
