# Generated by Django 5.0.6 on 2024-06-27 12:24

from django.db import migrations

from wis2box_adl.utils import create_default_data_parameters


def add_default_data_parameters(apps, schema_editor):
    create_default_data_parameters()


def backwards(apps, schema_editor):
    """nothing to do"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('wis2box_adl', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_data_parameters, backwards),
    ]
